### ISSUE TITLE
Work on android 5.1+ api 22

### ISSUE THREAD

**Issue by FloridaStream** [CharonChui/Vitamio#2]
this project work on android 5.1.0 on API 22 over genymotion emulator  x84 ?? I have an vitamio original sources in my project, and not work.

Vitamio is now DEPRECATED, you can continue this project? @CharonChui

**Comment by CharonChui** [comment]
Vitamio is not DEPRECATED. 
They published Vitamio 5.0.0 on 2015.11.02 and I will update this project to the newest version later.

**Comment by FloridaStream** [comment]
Okay, thank you for info, waiting for news =D
